/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";

interface TransactorInterface extends ethers.utils.Interface {
  functions: {
    "callFunction(address,(address,uint256),bytes)": FunctionFragment;
    "destruct(address)": FunctionFragment;
    "getExchange(uint8)": FunctionFragment;
    "owner()": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "trade(uint256,uint256,uint8,uint256,uint8,address,uint256,uint256)": FunctionFragment;
    "transferERC20(address,uint256,address)": FunctionFragment;
    "transferETH(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "callFunction",
    values: [string, { owner: string; number: BigNumberish }, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "destruct", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getExchange",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "trade",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferERC20",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferETH",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "callFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "destruct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferETH",
    data: BytesLike
  ): Result;

  events: {
    "SuccessfulTrade(address,uint256,uint8,uint256,uint8,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SuccessfulTrade"): EventFragment;
}

export type SuccessfulTradeEvent = TypedEvent<
  [string, BigNumber, number, BigNumber, number, BigNumber] & {
    tradedTokenAddress: string;
    borrowedWethAmount: BigNumber;
    sellingExchangeIndex: number;
    tradedTokenAmountOut: BigNumber;
    buyingExchangeIndex: number;
    wethAmountOut: BigNumber;
  }
>;

export class Transactor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TransactorInterface;

  functions: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    destruct(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getExchange(
      exchangeIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    setOwner(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    trade(
      expectedBlockNumber: BigNumberish,
      _wethAmountToBorrow: BigNumberish,
      _sellingExchangeIndex: BigNumberish,
      _wethAmountOutMin: BigNumberish,
      _buyingExchangeIndex: BigNumberish,
      _tradedToken: string,
      _tradedTokenAmountOutMin: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferERC20(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferETH(
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  callFunction(
    sender: string,
    accountInfo: { owner: string; number: BigNumberish },
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  destruct(
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getExchange(
    exchangeIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  setOwner(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  trade(
    expectedBlockNumber: BigNumberish,
    _wethAmountToBorrow: BigNumberish,
    _sellingExchangeIndex: BigNumberish,
    _wethAmountOutMin: BigNumberish,
    _buyingExchangeIndex: BigNumberish,
    _tradedToken: string,
    _tradedTokenAmountOutMin: BigNumberish,
    _deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferERC20(
    _token: string,
    _amount: BigNumberish,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferETH(
    _amount: BigNumberish,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    destruct(_to: string, overrides?: CallOverrides): Promise<void>;

    getExchange(
      exchangeIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    setOwner(_newOwner: string, overrides?: CallOverrides): Promise<void>;

    trade(
      expectedBlockNumber: BigNumberish,
      _wethAmountToBorrow: BigNumberish,
      _sellingExchangeIndex: BigNumberish,
      _wethAmountOutMin: BigNumberish,
      _buyingExchangeIndex: BigNumberish,
      _tradedToken: string,
      _tradedTokenAmountOutMin: BigNumberish,
      _deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferERC20(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferETH(
      _amount: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SuccessfulTrade(address,uint256,uint8,uint256,uint8,uint256)"(
      tradedTokenAddress?: null,
      borrowedWethAmount?: null,
      sellingExchangeIndex?: null,
      tradedTokenAmountOut?: null,
      buyingExchangeIndex?: null,
      wethAmountOut?: null
    ): TypedEventFilter<
      [string, BigNumber, number, BigNumber, number, BigNumber],
      {
        tradedTokenAddress: string;
        borrowedWethAmount: BigNumber;
        sellingExchangeIndex: number;
        tradedTokenAmountOut: BigNumber;
        buyingExchangeIndex: number;
        wethAmountOut: BigNumber;
      }
    >;

    SuccessfulTrade(
      tradedTokenAddress?: null,
      borrowedWethAmount?: null,
      sellingExchangeIndex?: null,
      tradedTokenAmountOut?: null,
      buyingExchangeIndex?: null,
      wethAmountOut?: null
    ): TypedEventFilter<
      [string, BigNumber, number, BigNumber, number, BigNumber],
      {
        tradedTokenAddress: string;
        borrowedWethAmount: BigNumber;
        sellingExchangeIndex: number;
        tradedTokenAmountOut: BigNumber;
        buyingExchangeIndex: number;
        wethAmountOut: BigNumber;
      }
    >;
  };

  estimateGas: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    destruct(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getExchange(
      exchangeIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    setOwner(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    trade(
      expectedBlockNumber: BigNumberish,
      _wethAmountToBorrow: BigNumberish,
      _sellingExchangeIndex: BigNumberish,
      _wethAmountOutMin: BigNumberish,
      _buyingExchangeIndex: BigNumberish,
      _tradedToken: string,
      _tradedTokenAmountOutMin: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferERC20(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferETH(
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    callFunction(
      sender: string,
      accountInfo: { owner: string; number: BigNumberish },
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    destruct(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getExchange(
      exchangeIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setOwner(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    trade(
      expectedBlockNumber: BigNumberish,
      _wethAmountToBorrow: BigNumberish,
      _sellingExchangeIndex: BigNumberish,
      _wethAmountOutMin: BigNumberish,
      _buyingExchangeIndex: BigNumberish,
      _tradedToken: string,
      _tradedTokenAmountOutMin: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferERC20(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferETH(
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
