/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKyberNetworkProxy,
  IKyberNetworkProxyInterface,
} from "../IKyberNetworkProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "src",
        type: "address",
      },
      {
        internalType: "contract IERC20",
        name: "dest",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "srcQty",
        type: "uint256",
      },
    ],
    name: "getExpectedRate",
    outputs: [
      {
        internalType: "uint256",
        name: "expectedRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "worstRate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "src",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "srcAmount",
        type: "uint256",
      },
      {
        internalType: "contract IERC20",
        name: "dest",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "minConversionRate",
        type: "uint256",
      },
    ],
    name: "swapTokenToToken",
    outputs: [
      {
        internalType: "uint256",
        name: "destAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKyberNetworkProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IKyberNetworkProxyInterface {
    return new utils.Interface(_abi) as IKyberNetworkProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKyberNetworkProxy {
    return new Contract(address, _abi, signerOrProvider) as IKyberNetworkProxy;
  }
}
