/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Actions, ActionsInterface } from "../Actions";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x5e124704",
        type: "bytes32",
      },
    ],
    name: "c_0x5e124704",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e0610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063c0bba1e8146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b6000813590506060816096565b92915050565b600060208284031215607757600080fd5b60006083848285016053565b91505092915050565b6000819050919050565b609d81608c565b811460a757600080fd5b5056fea2646970667358221220297bf6fe6c75dd9b9f4867d759e2400e2a24e0a4d84c0d1d8e775f19898131fb64736f6c63430008040033";

export class Actions__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Actions> {
    return super.deploy(overrides || {}) as Promise<Actions>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Actions {
    return super.attach(address) as Actions;
  }
  connect(signer: Signer): Actions__factory {
    return super.connect(signer) as Actions__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ActionsInterface {
    return new utils.Interface(_abi) as ActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Actions {
    return new Contract(address, _abi, signerOrProvider) as Actions;
  }
}
